services:
  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
      args:
        BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
        BETTER_AUTH_URL: ${BETTER_AUTH_URL}
        CORS_ORIGIN: ${CORS_ORIGIN}
        DATABASE_URL: ${DATABASE_URL}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        PORT: ${PORT:-3002}
    environment:
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - PORT=${PORT:-3002}
    expose:
      - ${PORT:-3002}
    networks:
      - dokploy-network

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      args:
        VITE_SERVER_URL: ${VITE_SERVER_URL}
        VITE_API_URL: ${VITE_API_URL}
    environment:
      - VITE_SERVER_URL=${VITE_SERVER_URL}
      - VITE_API_URL=${VITE_API_URL}
    expose:
      - 81
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
